export const RESTORE_NORMAL_STATES = [
    "USER_IN_RIDE",
    "PAUSED_BY_USER",
    "IN_OPS",
    "FRAUD",
    "DEPLOYED_FOR_RENTAL",
    "DEPLOYED_FOR_INTERNAL_USE",
    "CAR_SUBSCRIPTION",
    "BOOKED_BY_USER",
]

export const RESTORE_SLOW_STATES = [
    "AT_EXTERNAL_REPAIR",
    "AT_MILES_REPAIR",
    "AT_MILES_VRC",
    "AT_MOSTKI_BODYSHOP",
    "AT_MOSTKI_VRC",
    "AT_UPFITTING",
    "AT_UPFITTING ",
    "DOWNFITTED",
    "DOWNFITTING",
    "IN_CLAIMS",
    "IN_EXTERNAL_OPS",
    "IN_FIELD_REPAIR",
    "IN_LOGISTICS",
    "IN_REPAIR",
    "RETIRED",
    "UPFITTING",
]