version: '3.8'

services:

  scraper:
    image: koenidv/vorfahrt-scraper:latest-arm
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vorfahrt
      - DB_USER=****
      - DB_PASSWORD=****
      - INFLUX_URL=http://influx:8086
      - INFLUX_TOKEN=****
      - RPM_VEHICLE=100
      - RPM_MAP=120
      - RPM_PERCENTAGES=20
  
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  influx:
    image: influxdb:2.7.4
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influx:/var/lib/influxdb2
    

volumes:
  postgres:
    driver: local
  influx:
    driver: local