services:
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # local development only
    ports:
      - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data

  influx:
    image: influxdb:2.7.4
    ports:
      - "8086:8086"
    volumes:
      - influx:/var/lib/influxdb2

volumes:
  postgres:
    driver: local
  influx:
    driver: local
